--
ALTER TABLE TB_JOBS_ORDEM ADD COLUMN `VALOR_PAG` DECIMAL(10,2) NOT NULL DEFAULT 0 AFTER QTD;
ALTER TABLE TB_JOBS_ORDEM ADD COLUMN `VALOR_REC` DECIMAL(10,2) NOT NULL DEFAULT 0 AFTER VALOR_PAG;
--
--
SET SQL_SAFE_UPDATES = 0;
--
UPDATE TB_JOBS_ORDEM AS JO
INNER JOIN TB_JOB J ON J.COD_EMPRESA = JO.COD_EMPRESA
AND J.COD_JOB = JO.COD_JOB
SET JO.VALOR_PAG = J.VALOR_PAG, JO.VALOR_REC = J.VALOR_REC;
--
SET SQL_SAFE_UPDATES = 1;