--
-- Cria o cadastro das paginas
--
INSERT INTO `tb_paginas` (`COD_PAGINA`, `NOME_PAGINA`, `NOME_CONTROLADOR`, `FLG_ATIVO`, `COD_TIPO`, `FLG_TIPO_PAGINA`, `NIVEL_ACESSO`) 
VALUES ('4004', 'Filial', 'CD_Filial', 'S', '400', 'C', '98');
INSERT INTO `tb_paginas` (`COD_PAGINA`, `NOME_PAGINA`, `NOME_CONTROLADOR`, `FLG_ATIVO`, `COD_TIPO`, `FLG_TIPO_PAGINA`, `NIVEL_ACESSO`) 
VALUES ('4005', 'Tech x Filial', 'CD_UsuarioFilial', 'S', '400', 'C', '98');
--
-- Cria as colunas da filiais
--
ALTER TABLE TB_ORDEM ADD COLUMN COD_FILIAL INT NOT NULL DEFAULT 1 COMMENT 'Por padrão vamos sumir que a filial 1 sempre seja a matriz ela tem que existem no cadastro';
ALTER TABLE TB_JOB ADD COLUMN COD_FILIAL INT NOT NULL DEFAULT 1 COMMENT 'Por padrão vamos sumir que a filial 1 sempre seja a matriz ela tem que existem no cadastro';
ALTER TABLE TB_JOBS_USUARIO ADD COLUMN COD_FILIAL INT NOT NULL DEFAULT 1 COMMENT 'Por padrão vamos sumir que a filial 1 sempre seja a matriz ela tem que existem no cadastro';
ALTER TABLE TB_JOBS_ORDEM ADD COLUMN COD_FILIAL INT NOT NULL DEFAULT 1 COMMENT 'Por padrão vamos sumir que a filial 1 sempre seja a matriz ela tem que existem no cadastro';
--
-- Cria as chaves
--
ALTER TABLE TB_ORDEM ADD CONSTRAINT FK_TB_ORDEM_01 FOREIGN KEY(COD_EMPRESA, COD_FILIAL) REFERENCES TB_FILIAL(COD_EMPRESA, COD_FILIAL);
ALTER TABLE TB_JOB ADD CONSTRAINT FK_TB_JOB_01 FOREIGN KEY(COD_EMPRESA, COD_FILIAL) REFERENCES TB_FILIAL(COD_EMPRESA, COD_FILIAL);
ALTER TABLE TB_JOBS_USUARIO ADD CONSTRAINT FK_TB_JOBS_USUARIO_01 FOREIGN KEY(COD_EMPRESA, COD_FILIAL) REFERENCES TB_FILIAL(COD_EMPRESA, COD_FILIAL);
ALTER TABLE TB_JOBS_ORDEM ADD CONSTRAINT FK_TB_JOBS_ORDEM_01 FOREIGN KEY(COD_EMPRESA, COD_FILIAL) REFERENCES TB_FILIAL(COD_EMPRESA, COD_FILIAL);
--
--
-- Remove o relacionamento temporariamente
--
ALTER TABLE TB_JOBS_ORDEM DROP FOREIGN KEY fk_TB_JOBS_ORDEM_TB_ORDEM1;
-- 
-- Remove a PK
--
ALTER TABLE TB_ORDEM DROP PRIMARY KEY;
--
-- Cria a nova PK
--
ALTER TABLE TB_ORDEM ADD CONSTRAINT PRIMARY KEY(COD_EMPRESA, JOB_NUM, COD_FILIAL);
--
-- cria novamente
ALTER TABLE TB_JOBS_ORDEM ADD CONSTRAINT fk_TB_JOBS_ORDEM_TB_ORDEM1 FOREIGN KEY(COD_EMPRESA, JOB_NUM, COD_FILIAL) REFERENCES TB_ORDEM(COD_EMPRESA, JOB_NUM, COD_FILIAL);
--
-- Remove a PK
--
ALTER TABLE TB_JOBS_ORDEM DROP PRIMARY KEY; -- Se der erro em produção usar apenas o de baixo
--
ALTER TABLE TB_JOBS_ORDEM ADD CONSTRAINT PRIMARY KEY(COD_EMPRESA,JOB_NUM,COD_FILIAL,COD_JOB);
