-- CADASTRO DE USUARIO 
DROP TRIGGER IF EXISTS NOVO_USUARIO_JOB;
CREATE TRIGGER NOVO_USUARIO_JOB
AFTER INSERT
ON TB_USUARIOS FOR EACH ROW
INSERT INTO TB_JOBS_USUARIO (COD_JOB, COD_EMPRESA, COD_USUARIO, VALOR_PAG, VALOR_REC, QTD_MAX, QTD_MIN, FLG_ATIVO, COD_FILIAL)
SELECT 
   JB.COD_JOB, NEW.COD_EMPRESA, NEW.COD_USUARIO, JB.VALOR_PAG, JB.VALOR_REC, JB.QTD_MAX, JB.QTD_MIN, JB.FLG_ATIVO, JB.COD_FILIAL
FROM 
   TB_JOB AS JB WHERE JB.COD_EMPRESA = NEW.COD_EMPRESA AND JB.COD_FILIAL IN (SELECT COD_FILIAL FROM TB_USUARIO_FILIAL WHERE COD_USUARIO = NEW.COD_USUARIO AND JB.COD_EMPRESA = NEW.COD_EMPRESA);
-- 
-- DISPARA QUANDO CADASTRO DE NOVO JOB
--
DROP TRIGGER IF EXISTS NOVO_JOB;
CREATE TRIGGER NOVO_JOB
AFTER INSERT
ON TB_JOB FOR EACH ROW
INSERT INTO TB_JOBS_USUARIO (COD_JOB, COD_EMPRESA, COD_USUARIO, VALOR_PAG, VALOR_REC, QTD_MAX, QTD_MIN, FLG_ATIVO, COD_FILIAL)
SELECT 
   NEW.COD_JOB, US.COD_EMPRESA, US.COD_USUARIO, NEW.VALOR_PAG, NEW.VALOR_REC, NEW.QTD_MAX, NEW.QTD_MIN, NEW.FLG_ATIVO, NEW.COD_FILIAL
FROM 
   TB_USUARIOS AS US WHERE US.COD_EMPRESA = NEW.COD_EMPRESA AND NEW.COD_FILIAL IN (SELECT COD_FILIAL FROM TB_USUARIO_FILIAL WHERE COD_USUARIO = US.COD_USUARIO AND US.COD_EMPRESA = NEW.COD_EMPRESA);
--
-- CADASTRA QUANDO REALIZAR O VINCULO DE USUARIO COM A FILIAL
--
DROP TRIGGER IF EXISTS NOVA_FIALIAL_USUARIO;
CREATE TRIGGER NOVA_FIALIAL_USUARIO
AFTER INSERT
ON TB_USUARIO_FILIAL FOR EACH ROW
INSERT INTO TB_JOBS_USUARIO (COD_JOB, COD_EMPRESA, COD_USUARIO, VALOR_PAG, VALOR_REC, QTD_MAX, QTD_MIN, FLG_ATIVO, COD_FILIAL)
SELECT 
   JB.COD_JOB, NEW.COD_EMPRESA, NEW.COD_USUARIO, JB.VALOR_PAG, JB.VALOR_REC, JB.QTD_MAX, JB.QTD_MIN, JB.FLG_ATIVO, JB.COD_FILIAL
FROM 
   TB_JOB AS JB WHERE JB.COD_EMPRESA = NEW.COD_EMPRESA AND JB.COD_FILIAL = NEW.COD_FILIAL;
--
--
-- TRIGGER QUE QUANDO O CADASTRO DE UM JOB É APAGADO REMOVE TODOS OS RELACIONAMENTOS
-- DE USUARIOS PAGINAS.
-- 
DROP TRIGGER IF EXISTS DELETE_JOB_USUARIO;
CREATE TRIGGER DELETE_JOB_USUARIO
BEFORE DELETE
ON TB_JOB FOR EACH ROW
DELETE FROM TB_JOBS_USUARIO WHERE COD_JOB = OLD.COD_JOB AND COD_EMPRESA = OLD.COD_EMPRESA;
--
-- TRIGGER QUE QUANDO O CADASTRO DE UM USUARIO É APAGADO REMOVE TODOS OS RELACIONAMENTOS
-- DE JOBS.
-- 
DROP TRIGGER IF EXISTS DELETE_USUARIO_JOB;
CREATE TRIGGER DELETE_USUARIO_JOB
BEFORE DELETE
ON TB_USUARIOS FOR EACH ROW
DELETE FROM TB_JOBS_USUARIO WHERE COD_USUARIO = OLD.COD_USUARIO AND COD_EMPRESA = OLD.COD_EMPRESA;
--
--
/* INSERT INTO TB_JOBS_USUARIO (COD_JOB, COD_EMPRESA, COD_USUARIO, VALOR_PAG, VALOR_REC, QTD_MAX, QTD_MIN, FLG_ATIVO)
SELECT 
   JB.COD_JOB, US.COD_EMPRESA, US.COD_USUARIO, JB.VALOR_PAG, JB.VALOR_REC, JB.QTD_MAX, JB.QTD_MIN, JB.FLG_ATIVO
FROM 
   TB_JOB AS JB
   LEFT JOIN TB_USUARIOS AS US ON JB.COD_EMPRESA = US.COD_EMPRESA;*/
