-- MySQL Script generated by MySQL Workbench
-- Mon Nov 30 21:38:36 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema painel-clgas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `TB_EMPRESA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TB_EMPRESA` (
  `COD_EMPRESA` INT NOT NULL,
  `NOME_EMPRESA` VARCHAR(100) NOT NULL,
  `NOME_PORTAL` VARCHAR(50) NOT NULL,
  `DES_CHAVE` VARCHAR(300) NOT NULL COMMENT 'Poderia ser uma chave composta com informações da empresa, gerada no momento do cadastro da empresa, para ser retornado para o mobile, para que ele possa retornar quando solicitar alguma requisição.',
  `DATA_EXPIRACAO` DATETIME NOT NULL COMMENT 'Data limite que o cliente vai poder utilizar a aplicação até que ela pare e ele perca o acesso.\n',
  `DATA_ALTERACAO` DATETIME NOT NULL COMMENT 'Quando o registro for atualizado.',
  PRIMARY KEY (`COD_EMPRESA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TB_USUARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TB_USUARIOS` (
  `COD_EMPRESA` INT NOT NULL,
  `COD_USUARIO` INT NOT NULL AUTO_INCREMENT COMMENT 'código do usuário',
  `NOM_USUARIO` VARCHAR(100) NOT NULL COMMENT '\'nome do usuário\'',
  `LOGIN` VARCHAR(50) NOT NULL COMMENT 'nome de login do usuario, unico.',
  `SENHA` VARCHAR(20) NOT NULL,
  `FLG_ATIVO` VARCHAR(1) NOT NULL DEFAULT 'N' COMMENT 'conta ativa = S\nconta desativada = N',
  `FLG_TIPO_USUARIO` VARCHAR(1) NOT NULL DEFAULT 'C' COMMENT 'Vai existir dois tipos, (C) Comum e o (M) Master',
  `FLG_TIPO_ACESSO_APP` VARCHAR(1) NOT NULL DEFAULT 'N' COMMENT 'A - Admin acesso total\nC - Colaborador apenas na parte do negocio\nN - Sem acesso',
  PRIMARY KEY (`COD_USUARIO`, `COD_EMPRESA`),
  UNIQUE INDEX `LOGIN_UK` (`LOGIN` ASC),
  INDEX `TB_USUARIOS_TB_EMPRESA_FK` (`COD_EMPRESA` ASC),
  UNIQUE INDEX `COD_USUARIO_UK` (`COD_USUARIO` ASC),
  CONSTRAINT `TB_USUARIOS_TB_EMPRESA_FK`
    FOREIGN KEY (`COD_EMPRESA`)
    REFERENCES `TB_EMPRESA` (`COD_EMPRESA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TB_TIPOS_PAGINAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TB_TIPOS_PAGINAS` (
  `COD_TIPO` INT NOT NULL COMMENT 'Código do tipo\n',
  `CLASSE_CSS_ICON` VARCHAR(100) NOT NULL COMMENT 'A propriedade vai armazer a classe css que vai ser utilizada no menu para carregar o icones do menu, exemplo : \"fa fa-icon\"',
  `DESCRICAO` VARCHAR(50) NOT NULL COMMENT 'Nome da propriedadesm, exemplo Análise e etc.',
  PRIMARY KEY (`COD_TIPO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TB_PAGINAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TB_PAGINAS` (
  `COD_PAGINA` INT NOT NULL,
  `NOME_PAGINA` VARCHAR(50) NOT NULL,
  `NOME_CONTROLADOR` VARCHAR(50) NOT NULL,
  `FLG_ATIVO` VARCHAR(1) NOT NULL,
  `COD_TIPO` INT NOT NULL,
  `FLG_TIPO_PAGINA` VARCHAR(1) NOT NULL DEFAULT 'C' COMMENT 'Define o tipo de Pagina, (C) Comun e (M) Master, as paginas do tipo master apenas o admin geral tem acesso.',
  PRIMARY KEY (`COD_PAGINA`),
  INDEX `TB_PAGINA_TB_TIPO_PAGINA_FK` (`COD_TIPO` ASC),
  CONSTRAINT `TB_PAGINA_TB_TIPO_PAGINA_FK`
    FOREIGN KEY (`COD_TIPO`)
    REFERENCES `TB_TIPOS_PAGINAS` (`COD_TIPO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TB_TIPOS_ACESSOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TB_TIPOS_ACESSOS` (
  `COD_TIPO_ACESSO` INT NOT NULL COMMENT 'Código\n',
  `FLG_TIPO_ACESSO` VARCHAR(1) NOT NULL COMMENT 'A (ALTERAÇÃO), V (VISUALIZAÇÃO), N (NULL SEM ACESSO)',
  `DES_TIPO_ACESSO` VARCHAR(50) NOT NULL COMMENT 'Descrição do tipo de acesso para carregar no combo.',
  PRIMARY KEY (`COD_TIPO_ACESSO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TB_USUARIOS_PAGINAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TB_USUARIOS_PAGINAS` (
  `COD_PAGINA` INT NOT NULL,
  `COD_USUARIO` INT NOT NULL,
  `COD_EMPRESA` INT NOT NULL,
  `COD_TIPO_ACESSO` INT NOT NULL,
  PRIMARY KEY (`COD_PAGINA`, `COD_USUARIO`, `COD_EMPRESA`),
  INDEX `TB_USUARIOS_PAGINAS_TB_TIPOS_ACESSOS_FK` (`COD_TIPO_ACESSO` ASC),
  INDEX `TB_USUARIOS_PAGINAS_TB_USUARIOS_FK` (`COD_USUARIO` ASC, `COD_EMPRESA` ASC),
  CONSTRAINT `TB_USUARIOS_PAGINAS_TB_PAGINA_FK`
    FOREIGN KEY (`COD_PAGINA`)
    REFERENCES `TB_PAGINAS` (`COD_PAGINA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `TB_USUARIOS_PAGINAS_TB_TIPOS_ACESSOS_FK`
    FOREIGN KEY (`COD_TIPO_ACESSO`)
    REFERENCES `TB_TIPOS_ACESSOS` (`COD_TIPO_ACESSO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `TB_USUARIOS_PAGINAS_TB_USUARIOS_FK`
    FOREIGN KEY (`COD_USUARIO` , `COD_EMPRESA`)
    REFERENCES `TB_USUARIOS` (`COD_USUARIO` , `COD_EMPRESA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TB_LOGS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TB_LOGS` (
  `COD_LOG` INT NOT NULL AUTO_INCREMENT,
  `NOME_CONTROLLER` VARCHAR(50) NULL,
  `OPERACAO` VARCHAR(800) NULL,
  `DATA_EXCEPTION` DATETIME NOT NULL,
  `RESPOSTA_USUARIO` VARCHAR(400) NOT NULL,
  `EXCEPTION` VARCHAR(500) NULL,
  PRIMARY KEY (`COD_LOG`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TB_DISPOSITIVOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TB_DISPOSITIVOS` (
  `ID_DISPOSITIVO` INT(10) NOT NULL COMMENT 'Id do dispositivo gerado pelo portal.',
  `COD_EMPRESA` INT NOT NULL COMMENT 'Código da empresa',
  `COD_USUARIO` INT NOT NULL COMMENT 'Código do usuário  que realizaou o ultimo login no dispositivo.',
  `DES_ID_DISPOSITIVO` VARCHAR(100) NOT NULL COMMENT 'Id unico que gerado pelo portal para cada dispositivo o portal que gera e fica disponivel e visivel no aplicativo.',
  `TOKEN_FIREBASE` VARCHAR(1000) NOT NULL COMMENT 'Token que oi gerado pelo firebase.',
  PRIMARY KEY (`ID_DISPOSITIVO`, `COD_EMPRESA`),
  INDEX `TB_DISPOSITIVOS_TB_EMPRESA_FK` (`COD_EMPRESA` ASC),
  INDEX `TB_DISPOSITIVOS_TB_USUARIOS_FK` (`COD_USUARIO` ASC, `COD_EMPRESA` ASC),
  UNIQUE INDEX `DES_ID_DISPOSITIVO_UK` (`DES_ID_DISPOSITIVO` ASC),
  CONSTRAINT `TB_DISPOSITIVOS_TB_EMPRESA_FK`
    FOREIGN KEY (`COD_EMPRESA`)
    REFERENCES `TB_EMPRESA` (`COD_EMPRESA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `TB_DISPOSITIVOS_TB_USUARIOS_FK`
    FOREIGN KEY (`COD_USUARIO` , `COD_EMPRESA`)
    REFERENCES `TB_USUARIOS` (`COD_USUARIO` , `COD_EMPRESA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
