--
INSERT INTO tb_paginas (COD_PAGINA, NOME_PAGINA, NOME_CONTROLADOR, FLG_ATIVO, COD_TIPO, FLG_TIPO_PAGINA, NIVEL_ACESSO) 
VALUES ('3014', 'Report Simple 2 (QC)', 'CD_ReportsSimple2', 'S', '300', 'C', '5');
--