-- PARA VOLTAR PARA VERSÃO ANTERIOR UTILIZAR O SCRIPT 022
--
DROP EVENT IF EXISTS ATUALIZAR_STATUS_ORDEM;
--
DELIMITER //
--
CREATE EVENT ATUALIZAR_STATUS_ORDEM
ON SCHEDULE 
EVERY 1 DAY
STARTS CONCAT(DATE(CURRENT_TIMESTAMP) + INTERVAL 1 DAY,' 00:01:00')
DO
BEGIN    
    UPDATE TB_ORDEM AS OD
       SET OD.STATUS = 'Not finished'
     WHERE OD.COD_EMPRESA IN (1,3) 
       AND OD.STATUS = 'Pending'
       AND DATE(OD.DATA_AGEND) < CURRENT_DATE
       AND (
			 SELECT COUNT(0)
			   FROM TB_JOBS_ORDEM AS JO
			  WHERE JO.COD_EMPRESA = OD.COD_EMPRESA
			    AND JO.COD_FILIAL = OD.COD_FILIAL
                AND JO.COD_TIPO_ORDEM = OD.COD_TIPO_ORDEM
                AND JO.JOB_NUM = OD.JOB_NUM
                AND JO.ID_CORTE = OD.ID_CORTE
		   ) = 0;
END //
--
DELIMITER ;
--
SET GLOBAL event_scheduler = ON;
--