--
-- CADASTRA OS ITENS DO MENU 
--
INSERT INTO 
TB_TIPOS_PAGINAS 
(COD_TIPO, CLASSE_CSS_ICON, DESCRICAO) VALUES 
(100, ' fa-users-cog ', 'Controle de Acesso'),
(200, ' fa-cogs ', 'Cadastros');
--
-- CADASTRADA OS TIPOS DE ACESSO AS PAGINAS
--
INSERT INTO 
TB_TIPOS_ACESSOS 
(COD_TIPO_ACESSO,FLG_TIPO_ACESSO,DES_TIPO_ACESSO) VALUES
(1,'A','Alteração'), 
(2,'V','Visualização'),
(3,'N','Sem acesso');
--
-- 
-- CADASTRA AS TELAS BASICAS DO CONTROLE DE ACESSO
--
INSERT INTO TB_PAGINAS (COD_PAGINA, NOME_PAGINA, NOME_CONTROLADOR, FLG_ATIVO, COD_TIPO, FLG_TIPO_PAGINA) VALUES 
(1000,'Páginas','AC_Paginas','S',100,'M'),
(1001,'Usuários','AC_Usuarios','S',100,'C'),
(1002,'Usuários X Páginas','AC_UsuariosPaginas','S',100,'C'),
(1003,'Empresas','AC_Empresas','S',100,'M');
--
-- CADASTRA O USUÁRIO INICIAL
--
-- EMPRESA INICIAL DE TODO PROJETO
--
INSERT INTO TB_EMPRESA(COD_EMPRESA, NOME_EMPRESA, NOME_PORTAL, DES_CHAVE, DATA_EXPIRACAO, DATA_ALTERACAO) VALUES 
(1,'Guica', 'Guica' ,'Definir','2029-01-01 00:00:00', curdate());
--
INSERT INTO TB_USUARIOS(COD_EMPRESA, COD_USUARIO, NOM_USUARIO, LOGIN, SENHA, FLG_ATIVO, FLG_TIPO_USUARIO, FLG_TIPO_ACESSO_APP) VALUES
(1,1,'Guilherme Dorazzi','guilhermedorazzi@gmail.com','01020304','S','M','A');
--
COMMIT;
--