--
--
ALTER TABLE TB_USUARIOS ADD COLUMN FLG_FILD_MANAGER VARCHAR(1) NULL DEFAULT 'N' COMMENT 'Indica se o usuario é um fild manager';
ALTER TABLE TB_USUARIOS ADD COLUMN COD_FILD_MANAGER INT NULL COMMENT 'Coluna que identifica o código do fild manager do usuario.';
--
--
ALTER TABLE TB_JOB ADD COLUMN VALOR_REP DECIMAL(10,2) NOT NULL DEFAULT 0 COMMENT 'Valor que vai ser repassado para o fild manager';
ALTER TABLE TB_JOBS_USUARIO ADD COLUMN VALOR_REP DECIMAL(10,2) NOT NULL DEFAULT 0 COMMENT 'Valor que vai ser repassado para o fild manager';
ALTER TABLE TB_JOBS_ORDEM ADD COLUMN VALOR_REP DECIMAL(10,2) NOT NULL DEFAULT 0 COMMENT 'Valor que vai ser repassado para o fild manager';
--
-- ALTERAR AS TRIGGERS QUE EXISTE HOJE
--
-- CADASTRO DE USUARIO 
DROP TRIGGER IF EXISTS NOVO_USUARIO_JOB;
CREATE TRIGGER NOVO_USUARIO_JOB
AFTER INSERT
ON TB_USUARIOS FOR EACH ROW
INSERT INTO TB_JOBS_USUARIO (COD_JOB, COD_EMPRESA, COD_USUARIO, VALOR_PAG, VALOR_REC, QTD_MAX, QTD_MIN, FLG_ATIVO, COD_FILIAL, VALOR_REP)
SELECT 
   JB.COD_JOB, NEW.COD_EMPRESA, NEW.COD_USUARIO, JB.VALOR_PAG, JB.VALOR_REC, JB.QTD_MAX, JB.QTD_MIN, JB.FLG_ATIVO, JB.COD_FILIAL, JB.VALOR_REP
FROM 
   TB_JOB AS JB WHERE JB.COD_EMPRESA = NEW.COD_EMPRESA AND JB.COD_FILIAL IN (SELECT COD_FILIAL FROM TB_USUARIO_FILIAL WHERE COD_USUARIO = NEW.COD_USUARIO AND JB.COD_EMPRESA = NEW.COD_EMPRESA);
-- 
-- DISPARA QUANDO CADASTRO DE NOVO JOB
--
DROP TRIGGER IF EXISTS NOVO_JOB;
CREATE TRIGGER NOVO_JOB
AFTER INSERT
ON TB_JOB FOR EACH ROW
INSERT INTO TB_JOBS_USUARIO (COD_JOB, COD_EMPRESA, COD_USUARIO, VALOR_PAG, VALOR_REC, QTD_MAX, QTD_MIN, FLG_ATIVO, COD_FILIAL, VALOR_REP)
SELECT 
   NEW.COD_JOB, US.COD_EMPRESA, US.COD_USUARIO, NEW.VALOR_PAG, NEW.VALOR_REC, NEW.QTD_MAX, NEW.QTD_MIN, NEW.FLG_ATIVO, NEW.COD_FILIAL, NEW.VALOR_REP
FROM 
   TB_USUARIOS AS US WHERE US.COD_EMPRESA = NEW.COD_EMPRESA AND NEW.COD_FILIAL IN (SELECT COD_FILIAL FROM TB_USUARIO_FILIAL WHERE COD_USUARIO = US.COD_USUARIO AND US.COD_EMPRESA = NEW.COD_EMPRESA);
--
-- CADASTRA QUANDO REALIZAR O VINCULO DE USUARIO COM A FILIAL
--
DROP TRIGGER IF EXISTS NOVA_FIALIAL_USUARIO;
CREATE TRIGGER NOVA_FIALIAL_USUARIO
AFTER INSERT
ON TB_USUARIO_FILIAL FOR EACH ROW
INSERT INTO TB_JOBS_USUARIO (COD_JOB, COD_EMPRESA, COD_USUARIO, VALOR_PAG, VALOR_REC, QTD_MAX, QTD_MIN, FLG_ATIVO, COD_FILIAL, VALOR_REP)
SELECT 
   JB.COD_JOB, NEW.COD_EMPRESA, NEW.COD_USUARIO, JB.VALOR_PAG, JB.VALOR_REC, JB.QTD_MAX, JB.QTD_MIN, JB.FLG_ATIVO, JB.COD_FILIAL, JB.VALOR_REP
FROM 
   TB_JOB AS JB WHERE JB.COD_EMPRESA = NEW.COD_EMPRESA AND JB.COD_FILIAL = NEW.COD_FILIAL;
--

