--
INSERT INTO `tb_tipos_paginas` (`COD_TIPO`,`CLASSE_CSS_ICON`,`DESCRICAO`) VALUES (300,' fa-chart-line ','Reports');
--
INSERT INTO `tb_tipos_paginas` (`COD_TIPO`,`CLASSE_CSS_ICON`,`DESCRICAO`) VALUES (400,'fa-id-card','Records');
--
INSERT INTO `tb_paginas` (`COD_PAGINA`,`NOME_PAGINA`,`NOME_CONTROLADOR`,`FLG_ATIVO`,`COD_TIPO`,`FLG_TIPO_PAGINA`) VALUES (1004,'Services','AC_Usuarios','S',400,'C');
--
INSERT INTO `tb_paginas` (`COD_PAGINA`,`NOME_PAGINA`,`NOME_CONTROLADOR`,`FLG_ATIVO`,`COD_TIPO`,`FLG_TIPO_PAGINA`) VALUES (2001,'Orders','CD_Ordem','S',200,'C');
--
INSERT INTO `tb_paginas` (`COD_PAGINA`,`NOME_PAGINA`,`NOME_CONTROLADOR`,`FLG_ATIVO`,`COD_TIPO`,`FLG_TIPO_PAGINA`) VALUES (3000,'Reports','RE_Relatorios','S',300,'C');
--
INSERT INTO `tb_paginas` (`COD_PAGINA`,`NOME_PAGINA`,`NOME_CONTROLADOR`,`FLG_ATIVO`,`COD_TIPO`,`FLG_TIPO_PAGINA`) VALUES (3001,'Payment for Technicians','RE_Relatorios','S',300,'C');
--
INSERT INTO `tb_paginas` (`COD_PAGINA`,`NOME_PAGINA`,`NOME_CONTROLADOR`,`FLG_ATIVO`,`COD_TIPO`,`FLG_TIPO_PAGINA`) VALUES (3002,'Invoice','RE_Relatorios','S',300,'C');
--
INSERT INTO `tb_paginas` (`COD_PAGINA`,`NOME_PAGINA`,`NOME_CONTROLADOR`,`FLG_ATIVO`,`COD_TIPO`,`FLG_TIPO_PAGINA`) VALUES (3003,'Receipt Analysis','RE_Relatorios','S',300,'C');
--
INSERT INTO `tb_paginas` (`COD_PAGINA`,`NOME_PAGINA`,`NOME_CONTROLADOR`,`FLG_ATIVO`,`COD_TIPO`,`FLG_TIPO_PAGINA`) VALUES (3004,'Received X Paid','RE_Relatorios','S',300,'C');
--
INSERT INTO `tb_paginas` (`COD_PAGINA`,`NOME_PAGINA`,`NOME_CONTROLADOR`,`FLG_ATIVO`,`COD_TIPO`,`FLG_TIPO_PAGINA`) VALUES (3005,'Relatório Adriana','RE_Relatorios','S',300,'C');
