ALTER TABLE TB_FIELD_PAGA ADD COLUMN COD_USUARIO INT NOT NULL;
ALTER TABLE TB_FIELD_PAGA ADD INDEX FK_TB_FIELD_PAGA_04_IDX (COD_USUARIO ASC, COD_EMPRESA ASC);
ALTER TABLE TB_FIELD_PAGA ADD  CONSTRAINT FK_TB_FIELD_PAGA_04 FOREIGN KEY (COD_USUARIO,COD_EMPRESA) REFERENCES TB_USUARIOS (COD_USUARIO,COD_EMPRESA);