--
ALTER TABLE TB_JOB ADD COLUMN VALOR_DESC DECIMAL(10,2) NOT NULL DEFAULT 0 COMMENT 'Coluna que armazena o valor que é descontado do field manager pelo serviço';
--
ALTER TABLE TB_JOBS_USUARIO ADD COLUMN VALOR_DESC DECIMAL(10,2) NOT NULL DEFAULT 0 COMMENT 'Coluna que armazena o valor que é descontado do field manager pelo serviço';
--
ALTER TABLE TB_JOBS_ORDEM ADD COLUMN VALOR_DESC DECIMAL(10,2) NOT NULL DEFAULT 0 COMMENT 'Coluna que armazena o valor que é descontado do field manager pelo serviço';
ALTER TABLE TB_JOBS_ORDEM ADD COLUMN VALOR_DESC2 DECIMAL(10,2) NULL COMMENT 'Coluna que armazena o valor que é descontado do field manager pelo serviço';
--
--
DROP TRIGGER IF EXISTS NOVO_JOB;
-- 
CREATE TRIGGER NOVO_JOB
 AFTER INSERT
 ON TB_JOB FOR EACH ROW
 INSERT INTO TB_JOBS_USUARIO (COD_JOB, COD_EMPRESA, COD_USUARIO, VALOR_PAG, VALOR_REC, QTD_MAX, QTD_MIN, FLG_ATIVO, COD_FILIAL, VALOR_REP, VALOR_DESC)
 SELECT 
    NEW.COD_JOB, US.COD_EMPRESA, US.COD_USUARIO, NEW.VALOR_PAG, NEW.VALOR_REC, NEW.QTD_MAX, NEW.QTD_MIN, NEW.FLG_ATIVO, NEW.COD_FILIAL, NEW.VALOR_REP, NEW.VALOR_DESC
 FROM 
    TB_USUARIOS AS US WHERE US.COD_EMPRESA = NEW.COD_EMPRESA AND NEW.COD_FILIAL IN (SELECT COD_FILIAL FROM TB_USUARIO_FILIAL WHERE COD_USUARIO = US.COD_USUARIO AND US.COD_EMPRESA = NEW.COD_EMPRESA);
--
