--
--
ALTER TABLE TB_DIVIDA ADD COLUMN COD_FILIAL INT(11) NULL COMMENT 'Codigo da filial que pertence a divida';
--
ALTER TABLE TB_DIVIDA ADD CONSTRAINT `FK_TB_DESCONTOS_04` FOREIGN KEY (`COD_EMPRESA`, `COD_FILIAL`) REFERENCES `tb_filial` (`COD_EMPRESA`, `COD_FILIAL`);
--
--
SELECT COUNT(*) FROM TB_DIVIDA;
--
 UPDATE TB_DIVIDA AS DV
   JOIN TB_USUARIO_FILIAL AS UF
     ON UF.COD_EMPRESA = DV.COD_EMPRESA
    AND UF.COD_USUARIO = DV.COD_USUARIO
    SET DV.COD_FILIAL = UF.COD_FILIAL
  WHERE UF.FLG_PRINCIPAL = 'S';
--
