--
ALTER TABLE tb_usuarios ADD COLUMN `COD_FIELD_DIRECTOR` int(11) DEFAULT NULL COMMENT 'Coluna que identifica quem eh o subordinado do field director.';
--
-- ESSA TABELA VAI REALIZAR O PROCESSO DE TODAS AS AMARRACOES DOS USUARIOS E SEUS SUBORDINADOS. 
--
CREATE TABLE tb_usuarios_subordinados(
  ID INT(11) NOT NULL AUTO_INCREMENT,
  COD_EMPRESA int(11) NOT NULL,
  COD_USUARIO int(11) NOT NULL,
  COD_FILIAL int(11) NOT NULL,
  COD_USUARIO_SUBORDINADO int(11) NOT NULL,
  DATA_CADASTRO datetime null default current_timestamp(),
  PRIMARY KEY (ID),
  KEY FK_TB_USUARIOS_SUBORDINADOS_01_IDX (COD_EMPRESA, COD_FILIAL, COD_USUARIO),
  CONSTRAINT  UK_TB_USUARIOS_SUBORDINADOS_01 UNIQUE KEY(COD_EMPRESA,COD_FILIAL,COD_USUARIO,COD_USUARIO_SUBORDINADO),
  CONSTRAINT `FK_TB_USUARIOS_SUBORDINADOS_01` FOREIGN KEY (`COD_EMPRESA`) REFERENCES `tb_empresa` (`COD_EMPRESA`) ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT `FK_TB_USUARIOS_SUBORDINADOS_02` FOREIGN KEY (`COD_FILIAL`, `COD_EMPRESA`) REFERENCES `tb_filial` (`COD_FILIAL`, `COD_EMPRESA`) ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT `FK_TB_USUARIOS_SUBORDINADOS_03` FOREIGN KEY (`COD_USUARIO`, `COD_EMPRESA`) REFERENCES `tb_usuarios` (`COD_USUARIO`, `COD_EMPRESA`) ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT `FK_TB_USUARIOS_SUBORDINADOS_04` FOREIGN KEY (`COD_USUARIO_SUBORDINADO`, `COD_EMPRESA`) REFERENCES `tb_usuarios` (`COD_USUARIO`, `COD_EMPRESA`) ON DELETE CASCADE ON UPDATE NO ACTION
);
--
INSERT INTO `tb_paginas` (`COD_PAGINA`, `NOME_PAGINA`, `NOME_CONTROLADOR`, `FLG_ATIVO`, `COD_TIPO`, `FLG_TIPO_PAGINA`, `NIVEL_ACESSO`) 
VALUES ('4008', 'Users X Groups', 'CD_GroupUsers', 'S', '400', 'C', '98');

