--
ALTER TABLE tb_usuarios ADD COLUMN PERCENTUAL_DESCONTO INT NOT NULL DEFAULT 5 COMMENT 'Qual o percentual maximo de desconto que sera aplicado para o tech';
ALTER TABLE tb_usuarios ADD COLUMN VALOR_DESCONTO_MAXIMO DECIMAL(8,2) NOT NULL DEFAULT 0.00 COMMENT 'Valor maximo que pode ser desconto do usuario';
--
/*
CREATE TABLE TB_VALORES_RETIDOS(
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `COD_EMPRESA` int(11) NOT NULL,
  `COD_USUARIO` int(11) NOT NULL,
  `COD_FILIAL` int(11) DEFAULT NULL,
  `VALOR_TOTAL` decimal(10,2) NOT NULL,
  `DATA_ATUALIZACAO` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`ID`),
  CONSTRAINT UNIQUE KEY (COD_EMPRESA,COD_USUARIO,COD_FILIAL),
  CONSTRAINT FK_TB_VALORES_RETIDOS_01 FOREIGN KEY (`COD_EMPRESA`) REFERENCES `tb_empresa` (`COD_EMPRESA`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_TB_VALORES_RETIDOS_02 FOREIGN KEY (`COD_USUARIO`, `COD_EMPRESA`) REFERENCES `tb_usuarios` (`COD_USUARIO`, `COD_EMPRESA`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_TB_VALORES_RETIDOS_03 FOREIGN KEY (`COD_EMPRESA`, `COD_FILIAL`) REFERENCES `tb_filial` (`COD_EMPRESA`, `COD_FILIAL`)
);
--
CREATE TABLE TB_VALORES_RETIDOS_CREDITO(
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `COD_EMPRESA` int(11) NOT NULL,
  `COD_USUARIO` int(11) NOT NULL,
  `COD_FILIAL` int(11) DEFAULT NULL,
  `ID_ORDEM` int(20) NOT NULL COMMENT 'ID DA ORDEM EM QUE ESTA SENDO REALIZADO O DESCONTO DO TECH',
  `TIPO` VARCHAR(100) DEFAULT NULL,
  `MOTIVO` VARCHAR(100) DEFAULT NULL,
  `VALOR` decimal(10,2) NOT NULL,
  `DATA_ATUALIZACAO` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`ID`),
  CONSTRAINT FK_TB_VALORES_RETIDOS_01 FOREIGN KEY (`COD_EMPRESA`) REFERENCES `tb_empresa` (`COD_EMPRESA`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_TB_VALORES_RETIDOS_02 FOREIGN KEY (`COD_USUARIO`, `COD_EMPRESA`) REFERENCES `tb_usuarios` (`COD_USUARIO`, `COD_EMPRESA`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_TB_VALORES_RETIDOS_03 FOREIGN KEY (`COD_EMPRESA`, `COD_FILIAL`) REFERENCES `tb_filial` (`COD_EMPRESA`, `COD_FILIAL`)
);
--
CREATE TABLE TB_VALORES_RETIDOS_DEBITO(
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `COD_EMPRESA` int(11) NOT NULL,
  `COD_USUARIO` int(11) NOT NULL,
  `COD_FILIAL` int(11) DEFAULT NULL,
  `TIPO` VARCHAR(100) DEFAULT NULL,
  `MOTIVO` VARCHAR(100) DEFAULT NULL,
  `VALOR` decimal(10,2) NOT NULL,
  `DATA_ATUALIZACAO` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`ID`),
  CONSTRAINT FK_TB_VALORES_RETIDOS_01 FOREIGN KEY (`COD_EMPRESA`) REFERENCES `tb_empresa` (`COD_EMPRESA`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_TB_VALORES_RETIDOS_02 FOREIGN KEY (`COD_USUARIO`, `COD_EMPRESA`) REFERENCES `tb_usuarios` (`COD_USUARIO`, `COD_EMPRESA`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_TB_VALORES_RETIDOS_03 FOREIGN KEY (`COD_EMPRESA`, `COD_FILIAL`) REFERENCES `tb_filial` (`COD_EMPRESA`, `COD_FILIAL`)
);
--
--
-- CRIAR A PROCEDURE QUE VAI GERAR ESSAS INFORMACOES PRA MIM.
select PERCENTUAL_DESCONTO, VALOR_DESCONTO_MAXIMO from tb_usuarios where COD_EMPRESA = 1 and COD_USUARIO = 1;
--
*/

