-- MySQL Script generated by MySQL Workbench
-- Mon Mar  2 20:19:31 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema painel-controle-acesso
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `TB_USUARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TB_USUARIOS` (
  `COD_USUARIO` INT NOT NULL AUTO_INCREMENT COMMENT 'código do usuário',
  `NOM_USUARIO` VARCHAR(100) NOT NULL COMMENT '\'nome do usuário\'',
  `LOGIN` VARCHAR(50) NOT NULL COMMENT 'nome de login do usuario, unico.',
  `SENHA` VARCHAR(20) NOT NULL,
  `FLG_ATIVO` VARCHAR(1) NOT NULL DEFAULT 'N' COMMENT 'conta ativa = S\nconta desativada = N',
  `FLG_TIPO_USUARIO` VARCHAR(1) NOT NULL DEFAULT 'C' COMMENT 'Vai existir dois tipos, (C) Comum e o (M) Master',
  PRIMARY KEY (`COD_USUARIO`),
  UNIQUE INDEX `LOGIN_UNIQUE` (`LOGIN` ASC))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `TB_TIPOS_PAGINAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TB_TIPOS_PAGINAS` (
  `COD_TIPO` INT NOT NULL COMMENT 'Código do tipo\n',
  `CLASSE_CSS_ICON` VARCHAR(100) NOT NULL COMMENT 'A propriedade vai armazer a classe css que vai ser utilizada no menu para carregar o icones do menu, exemplo : \"fa fa-icon\"',
  `DESCRICAO` VARCHAR(50) NOT NULL COMMENT 'Nome da propriedadesm, exemplo Análise e etc.',
  PRIMARY KEY (`COD_TIPO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TB_PAGINAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TB_PAGINAS` (
  `COD_PAGINA` INT NOT NULL,
  `NOME_PAGINA` VARCHAR(50) NOT NULL,
  `NOME_CONTROLADOR` VARCHAR(50) NOT NULL,
  `FLG_ATIVO` VARCHAR(1) NOT NULL DEFAULT 'S',  
  `FLG_TIPO_PAGINA` VARCHAR(1) NOT NULL DEFAULT 'C' COMMENT 'Define o tipo de Pagina, (C) Comun e (M) Master, as paginas do tipo master apenas o admin geral tem acesso.',
  `COD_TIPO` INT NOT NULL,
  PRIMARY KEY (`COD_PAGINA`),
  INDEX `fk_TB_PAGINA_TB_TIPO_PAGINA1_idx` (`COD_TIPO` ASC),
  CONSTRAINT `fk_TB_PAGINA_TB_TIPO_PAGINA1`
    FOREIGN KEY (`COD_TIPO`)
    REFERENCES `TB_TIPOS_PAGINAS` (`COD_TIPO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TB_TIPOS_ACESSOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TB_TIPOS_ACESSOS` (
  `COD_TIPO_ACESSO` INT NOT NULL COMMENT 'Código\n',
  `FLG_TIPO_ACESSO` VARCHAR(1) NOT NULL COMMENT 'A (ALTERAÇÃO), V (VISUALIZAÇÃO), N (NULL SEM ACESSO)',
  `DES_TIPO_ACESSO` VARCHAR(50) NOT NULL COMMENT 'Descrição do tipo de acesso para carregar no combo.',
  PRIMARY KEY (`COD_TIPO_ACESSO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TB_USUARIOS_PAGINAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TB_USUARIOS_PAGINAS` (
  `COD_PAGINA` INT NOT NULL,
  `COD_USUARIO` INT NOT NULL,
  `COD_TIPO_ACESSO` INT NOT NULL,
  PRIMARY KEY (`COD_PAGINA`, `COD_USUARIO`),
  INDEX `fk_TB_USUARIOS_PAGINAS_TB_Usuario1_idx` (`COD_USUARIO` ASC),
  INDEX `fk_TB_USUARIOS_PAGINAS_TB_TIPOS_ACESSOS1_idx` (`COD_TIPO_ACESSO` ASC),
  CONSTRAINT `fk_TB_USUARIOS_PAGINAS_TB_PAGINA1`
    FOREIGN KEY (`COD_PAGINA`)
    REFERENCES `TB_PAGINAS` (`COD_PAGINA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TB_USUARIOS_PAGINAS_TB_Usuario1`
    FOREIGN KEY (`COD_USUARIO`)
    REFERENCES `TB_USUARIOS` (`COD_USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TB_USUARIOS_PAGINAS_TB_TIPOS_ACESSOS1`
    FOREIGN KEY (`COD_TIPO_ACESSO`)
    REFERENCES `TB_TIPOS_ACESSOS` (`COD_TIPO_ACESSO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TB_LOGS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TB_LOGS` (
  `COD_LOG` INT NOT NULL AUTO_INCREMENT,
  `NOME_CONTROLLER` VARCHAR(50) NULL,
  `OPERACAO` VARCHAR(800) NULL,
  `DATA_EXCEPTION` DATETIME NOT NULL,
  `RESPOSTA_USUARIO` VARCHAR(400) NOT NULL,
  PRIMARY KEY (`COD_LOG`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
