-- CADASTRO DE USUARIO 
CREATE TRIGGER NOVO_USUARIO
AFTER INSERT
ON TB_USUARIOS FOR EACH ROW
INSERT INTO TB_USUARIOS_PAGINAS (COD_PAGINA, COD_USUARIO, COD_TIPO_ACESSO)
SELECT 
   PG.COD_PAGINA, NEW.COD_USUARIO, 3 AS COD_TIPO_ACESSO
FROM 
   TB_PAGINAS AS PG;
-- 
-- DISPARA QUANDO UMA PAGINA FOR CADASTRADA
--
CREATE TRIGGER NOVA_PAGINA
AFTER INSERT
ON TB_PAGINAS FOR EACH ROW
INSERT INTO TB_USUARIOS_PAGINAS (COD_PAGINA, COD_USUARIO, COD_TIPO_ACESSO)
SELECT 
   NEW.COD_PAGINA, US.COD_USUARIO, 3 AS COD_TIPO_ACESSO
FROM 
   TB_USUARIOS AS US;
--
-- TRIGGER QUE QUANDO O CADASTRO DE UMA PAGINA É APAGADO REMOVE TODOS OS RELACIONAMENTOS
-- DE USUARIOS PAGINAS.
-- 
CREATE TRIGGER DELETE_PAGINA
BEFORE DELETE
ON TB_PAGINAS FOR EACH ROW
DELETE FROM TB_USUARIOS_PAGINAS WHERE COD_PAGINA = OLD.COD_PAGINA;
--
-- TRIGGER QUE QUANDO O CADASTRO DE UM USUARIO É APAGADO REMOVE TODOS OS RELACIONAMENTOS
-- DE USUARIOS PAGINAS.
-- 
CREATE TRIGGER DELETE_USUARIO
BEFORE DELETE
ON TB_USUARIOS FOR EACH ROW
DELETE FROM TB_USUARIOS_PAGINAS WHERE COD_USUARIO = OLD.COD_USUARIO;