-- CADASTRA AS TELAS BASICAS PARA O CONTROLE DE ACESSO
--
INSERT INTO TB_PAGINAS (COD_PAGINA, NOME_PAGINA, NOME_CONTROLADOR, FLG_ATIVO, COD_TIPO, FLG_TIPO_PAGINA) VALUES 
(1000,'Páginas','AC_Paginas','S',100,'M'),
(1001,'Usuários','AC_Usuarios','S',100,'C'),
(1002,'Usuários X Páginas','AC_UsuariosPaginas','S',100,'C');