-- CADASTRO DE USUARIO 
DROP TRIGGER IF EXISTS NOVO_USUARIO_JOB;
CREATE TRIGGER NOVO_USUARIO_JOB
AFTER INSERT
ON TB_USUARIOS FOR EACH ROW
INSERT INTO TB_JOBS_USUARIO (COD_JOB, COD_EMPRESA, COD_USUARIO, VALOR_PAG, VALOR_REC, QTD_MAX, QTD_MIN, FLG_ATIVO)
SELECT 
   JB.COD_JOB, NEW.COD_EMPRESA, NEW.COD_USUARIO, JB.VALOR_PAG, JB.VALOR_REC, JB.QTD_MAX, JB.QTD_MIN, JB.FLG_ATIVO
FROM 
   TB_JOB AS JB;
-- 
-- DISPARA QUANDO UMA PAGINA FOR CADASTRADA
--
DROP TRIGGER IF EXISTS NOVO_JOB;
CREATE TRIGGER NOVO_JOB
AFTER INSERT
ON TB_JOB FOR EACH ROW
INSERT INTO TB_JOBS_USUARIO (COD_JOB, COD_EMPRESA, COD_USUARIO, VALOR_PAG, VALOR_REC, QTD_MAX, QTD_MIN, FLG_ATIVO)
SELECT 
   NEW.COD_JOB, US.COD_EMPRESA, US.COD_USUARIO, NEW.VALOR_PAG, NEW.VALOR_REC, NEW.QTD_MAX, NEW.QTD_MIN, NEW.FLG_ATIVO
FROM 
   TB_USUARIOS AS US;
--
-- TRIGGER QUE QUANDO O CADASTRO DE UM JOB É APAGADO REMOVE TODOS OS RELACIONAMENTOS
-- DE USUARIOS PAGINAS.
-- 
DROP TRIGGER IF EXISTS DELETE_JOB_USUARIO;
CREATE TRIGGER DELETE_JOB_USUARIO
BEFORE DELETE
ON TB_JOB FOR EACH ROW
DELETE FROM TB_JOBS_USUARIO WHERE COD_JOB = OLD.COD_JOB AND COD_EMPRESA = OLD.COD_EMPRESA;
--
-- TRIGGER QUE QUANDO O CADASTRO DE UM USUARIO É APAGADO REMOVE TODOS OS RELACIONAMENTOS
-- DE JOBS.
-- 
DROP TRIGGER IF EXISTS DELETE_USUARIO_JOB;
CREATE TRIGGER DELETE_USUARIO_JOB
BEFORE DELETE
ON TB_USUARIOS FOR EACH ROW
DELETE FROM TB_JOBS_USUARIO WHERE COD_USUARIO = OLD.COD_USUARIO AND COD_EMPRESA = OLD.COD_EMPRESA;
--
--
/* INSERT INTO TB_JOBS_USUARIO (COD_JOB, COD_EMPRESA, COD_USUARIO, VALOR_PAG, VALOR_REC, QTD_MAX, QTD_MIN, FLG_ATIVO)
SELECT 
   JB.COD_JOB, US.COD_EMPRESA, US.COD_USUARIO, JB.VALOR_PAG, JB.VALOR_REC, JB.QTD_MAX, JB.QTD_MIN, JB.FLG_ATIVO
FROM 
   TB_JOB AS JB
   LEFT JOIN TB_USUARIOS AS US ON JB.COD_EMPRESA = US.COD_EMPRESA;*/
