-- CADASTRO DE USUARIO 
DROP TRIGGER IF EXISTS NOVO_USUARIO;
CREATE TRIGGER NOVO_USUARIO
AFTER INSERT
ON TB_USUARIOS FOR EACH ROW
INSERT INTO TB_USUARIOS_PAGINAS (COD_PAGINA, COD_EMPRESA, COD_USUARIO, COD_TIPO_ACESSO)
SELECT 
   PG.COD_PAGINA, NEW.COD_EMPRESA, NEW.COD_USUARIO, IF(PG.NIVEL_ACESSO <= (SELECT NIVEL_ACESSO FROM TB_GRUPO WHERE GRUTECH = NEW.GRUTECH LIMIT 1), 1, 3) AS COD_TIPO_ACESSO
FROM 
   TB_PAGINAS AS PG;
-- 
-- DISPARA QUANDO UMA PAGINA FOR CADASTRADA
--
DROP TRIGGER IF EXISTS NOVA_PAGINA;
CREATE TRIGGER NOVA_PAGINA
AFTER INSERT
ON TB_PAGINAS FOR EACH ROW
INSERT INTO TB_USUARIOS_PAGINAS (COD_PAGINA, COD_EMPRESA, COD_USUARIO, COD_TIPO_ACESSO)
SELECT 
   NEW.COD_PAGINA, US.COD_EMPRESA, US.COD_USUARIO, IF(NEW.NIVEL_ACESSO <= (SELECT NIVEL_ACESSO FROM TB_GRUPO WHERE GRUTECH = US.GRUTECH LIMIT 1), 1, 3) AS COD_TIPO_ACESSO
FROM 
   TB_USUARIOS AS US;
--