--
ALTER TABLE TB_ORDEM ADD COLUMN `TEM_IMAGEM` VARCHAR(1) NULL DEFAULT 'N' COMMENT 'Coluna que vai gravar se uma ordem de serviço tem ou não imagem relacionada (Valores vão varia de S e N)';
--
-- TRIGGER QUE VAI ALIMENTAR A COLUNA QUE INDICA SE TEM OU NÃO IMAGEM
--
DROP TRIGGER IF EXISTS ADD_IMAGEM;
CREATE TRIGGER ADD_IMAGEM
AFTER INSERT
ON TB_IMAGENS FOR EACH ROW
UPDATE TB_ORDEM SET TEM_IMAGEM = 'S' 
 WHERE COD_EMPRESA = NEW.COD_EMPRESA 
   AND COD_FILIAL = NEW.COD_FILIAL 
   AND JOB_NUM = NEW.JOB_NUM 
   AND COD_TIPO_ORDEM = NEW.COD_TIPO_ORDEM;
--
DROP TRIGGER IF EXISTS DELETE_IMAGEM;
CREATE TRIGGER DELETE_IMAGEM
AFTER DELETE
ON TB_IMAGENS FOR EACH ROW
UPDATE TB_ORDEM SET TEM_IMAGEM = 'N' 
 WHERE COD_EMPRESA = OLD.COD_EMPRESA 
   AND COD_FILIAL = OLD.COD_FILIAL 
   AND JOB_NUM = OLD.JOB_NUM 
   AND COD_TIPO_ORDEM = OLD.COD_TIPO_ORDEM
   AND (SELECT COUNT(0) 
           FROM TB_IMAGENS 
		  WHERE COD_EMPRESA = OLD.COD_EMPRESA 
            AND COD_FILIAL = OLD.COD_FILIAL 
			AND JOB_NUM = OLD.JOB_NUM 
			AND COD_TIPO_ORDEM = OLD.COD_TIPO_ORDEM) = 0;
--
--
SET SQL_SAFE_UPDATES = 0;
UPDATE TB_ORDEM AS OD SET OD.TEM_IMAGEM = 'S' 
 WHERE EXISTS (
    SELECT 1
    FROM TB_IMAGENS AS IM
    WHERE OD.COD_EMPRESA = IM.COD_EMPRESA 
	  AND OD.COD_FILIAL = IM.COD_FILIAL 
	  AND OD.JOB_NUM = IM.JOB_NUM 
	  AND OD.COD_TIPO_ORDEM = IM.COD_TIPO_ORDEM
);
SET SQL_SAFE_UPDATES = 1;
--
--