--
ALTER TABLE TB_EMPRESA ADD COLUMN URL_LOGO VARCHAR(500) NULL COMMENT 'Armazena a url da imagem da empresa';
--
ALTER TABLE TB_FILIAL ADD COLUMN URL_LOGO VARCHAR(500) NULL COMMENT 'Armazena a url da imagem da empresa';
ALTER TABLE TB_FILIAL ADD COLUMN VALOR_EXP DECIMAL(10,2) NOT NULL DEFAULT 0 COMMENT '';
ALTER TABLE TB_FILIAL ADD COLUMN VALOR_IMP DECIMAL(10,2) NOT NULL DEFAULT 0 COMMENT '';
