--
-- CADASTRA OS ITENS DO MENU 
--
INSERT INTO 
TB_TIPOS_PAGINAS 
(COD_TIPO, CLASSE_CSS_ICON, DESCRICAO) VALUES 
(100,' fa-users-cog ','Acess Controll'),
(200,' fa-cogs ','Orders'),
(300,' fa-chart-line ','Reports'),
(400,'fa-id-card','Records');
--
-- CADASTRADA OS TIPOS DE ACESSO AS PAGINAS
--
INSERT INTO 
TB_TIPOS_ACESSOS 
(COD_TIPO_ACESSO,FLG_TIPO_ACESSO,DES_TIPO_ACESSO) VALUES
(1,'A','Alteração'), 
(2,'V','Visualização'),
(3,'N','Sem acesso');
--
-- 
-- CADASTRA AS TELAS BASICAS DO CONTROLE DE ACESSO
--
-- '100', ' fa-users-cog ', 'Acess Controll'
INSERT INTO `tb_paginas` (`COD_PAGINA`,`NOME_PAGINA`,`NOME_CONTROLADOR`,`FLG_ATIVO`,`COD_TIPO`,`FLG_TIPO_PAGINA`) VALUES (1000,'Pages','AC_Paginas','S',100,'M');
INSERT INTO `tb_paginas` (`COD_PAGINA`,`NOME_PAGINA`,`NOME_CONTROLADOR`,`FLG_ATIVO`,`COD_TIPO`,`FLG_TIPO_PAGINA`) VALUES (1002,'User X Page','AC_UsuariosPaginas','S',100,'C');
-- '200', ' fa-cogs ', 'Orders'
INSERT INTO `tb_paginas` (`COD_PAGINA`,`NOME_PAGINA`,`NOME_CONTROLADOR`,`FLG_ATIVO`,`COD_TIPO`,`FLG_TIPO_PAGINA`) VALUES (2001,'Orders Fake','CD_OrdemBK','S',200,'C');
INSERT INTO `tb_paginas` (`COD_PAGINA`,`NOME_PAGINA`,`NOME_CONTROLADOR`,`FLG_ATIVO`,`COD_TIPO`,`FLG_TIPO_PAGINA`) VALUES (2002,'Orders','CD_Ordem','S',200,'C');
-- '300', ' fa-chart-line ', 'Reports'
INSERT INTO `tb_paginas` (`COD_PAGINA`,`NOME_PAGINA`,`NOME_CONTROLADOR`,`FLG_ATIVO`,`COD_TIPO`,`FLG_TIPO_PAGINA`) VALUES (3000,'Reports','RE_Relatorios','S',300,'C');
-- '400', 'fa-id-card', 'Records'
INSERT INTO `tb_paginas` (`COD_PAGINA`,`NOME_PAGINA`,`NOME_CONTROLADOR`,`FLG_ATIVO`,`COD_TIPO`,`FLG_TIPO_PAGINA`) VALUES (1003,'Company','AC_Empresas','S',400,'M');
INSERT INTO `tb_paginas` (`COD_PAGINA`,`NOME_PAGINA`,`NOME_CONTROLADOR`,`FLG_ATIVO`,`COD_TIPO`,`FLG_TIPO_PAGINA`) VALUES (1004,'Users','AC_Usuarios','S',400,'C');
INSERT INTO `tb_paginas` (`COD_PAGINA`,`NOME_PAGINA`,`NOME_CONTROLADOR`,`FLG_ATIVO`,`COD_TIPO`,`FLG_TIPO_PAGINA`) VALUES (4001,'Citys','CD_Cidade','S',400,'C');
INSERT INTO `tb_paginas` (`COD_PAGINA`,`NOME_PAGINA`,`NOME_CONTROLADOR`,`FLG_ATIVO`,`COD_TIPO`,`FLG_TIPO_PAGINA`) VALUES (4002,'Jobs','CD_Job','S',400,'C');

--
-- CADASTRA O USUÁRIO INICIAL
--
-- EMPRESA INICIAL DE TODO PROJETO
--
INSERT INTO TB_EMPRESA(COD_EMPRESA, NOME_EMPRESA, NOME_PORTAL, DES_CHAVE, DATA_EXPIRACAO, DATA_ALTERACAO) VALUES 
(1,'Guica', 'Guica' ,'Definir','2029-01-01 00:00:00', curdate());
--
INSERT INTO TB_USUARIOS(COD_EMPRESA, COD_USUARIO, NOM_USUARIO, LOGIN, SENHA, FLG_ATIVO, FLG_TIPO_USUARIO, FLG_TIPO_ACESSO_APP) VALUES
(1,1,'Guilherme Dorazzi','guilhermedorazzi@gmail.com','01020304','S','M','A');
--
COMMIT;
--