--
ALTER TABLE tb_imagens_bk DROP FOREIGN KEY FK_TB_IMAGENS_01;
ALTER TABLE tb_imagens_bk DROP FOREIGN KEY FK_TB_IMAGENS_02;
--
ALTER TABLE tb_jobs_ordem_bk DROP FOREIGN KEY FK_TB_JOBS_ORDEM_01;
ALTER TABLE tb_jobs_ordem_bk DROP FOREIGN KEY fk_TB_JOBS_ORDEM_TB_EMPRESA1;
ALTER TABLE tb_jobs_ordem_bk DROP FOREIGN KEY fk_TB_JOBS_ORDEM_TB_ORDEM1;
--
ALTER TABLE tb_ordem_bk DROP FOREIGN KEY FK_TB_ORDEM_01;
ALTER TABLE tb_ordem_bk DROP FOREIGN KEY FK_TB_ORDEM_03;
ALTER TABLE tb_ordem_bk DROP FOREIGN KEY FK_TB_ORDEM_04;
ALTER TABLE tb_ordem_bk DROP FOREIGN KEY fk_TB_ORDEM_TB_CIDADE1;
ALTER TABLE tb_ordem_bk DROP FOREIGN KEY fk_TB_ORDEM_TB_EMPRESA1;
ALTER TABLE tb_ordem_bk DROP FOREIGN KEY fk_TB_ORDEM_TB_USUARIOS1;
--
--