-- 
-- COMO FOI SOLICITADO VAMOS RENOMEAR O ENUM TEMOS QUE FAZER UM UPDATE NO BANCO TAMBÉM PARA EQUALIZAR OS REGISTROS QUE FORAM CRIADOS 
--
SET SQL_SAFE_UPDATES = 0;
--
UPDATE TB_DIVIDA 
SET TIPO_DIVIDA = 'One Time'
WHERE TIPO_DIVIDA = 'Interval of days';
--
SET SQL_SAFE_UPDATES = 1;
--