--
DROP TRIGGER IF EXISTS NOVA_FIALIAL_USUARIO;
DROP TRIGGER IF EXISTS NOVA_FILIAL_USUARIO;
--
CREATE TRIGGER NOVA_FILIAL_USUARIO
 AFTER INSERT
 ON TB_USUARIO_FILIAL FOR EACH ROW
 INSERT INTO TB_JOBS_USUARIO (COD_JOB, COD_EMPRESA, COD_USUARIO, VALOR_PAG, VALOR_REC, QTD_MAX, QTD_MIN, FLG_ATIVO, COD_FILIAL, VALOR_REP, VALOR_DESC)
 SELECT 
    JB.COD_JOB, NEW.COD_EMPRESA, NEW.COD_USUARIO, JB.VALOR_PAG, JB.VALOR_REC, JB.QTD_MAX, JB.QTD_MIN, JB.FLG_ATIVO, JB.COD_FILIAL, JB.VALOR_REP, JB.VALOR_DESC
 FROM 
    TB_JOB AS JB WHERE JB.COD_EMPRESA = NEW.COD_EMPRESA AND JB.COD_FILIAL = NEW.COD_FILIAL
  ON DUPLICATE KEY UPDATE VALOR_PAG = VALUES(VALOR_PAG), VALOR_REC = VALUES(VALOR_REC), QTD_MAX = VALUES(QTD_MAX), QTD_MIN = VALUES(QTD_MIN), VALOR_REP = VALUES(VALOR_REP) , VALOR_DESC = VALUES(VALOR_DESC);