--
ALTER TABLE tb_tipos_paginas ADD COLUMN ORDEM_MENU INT NOT NULL DEFAULT 0;
UPDATE `tb_tipos_paginas` SET `ORDEM_MENU` = '1' WHERE (`COD_TIPO` = '400');
UPDATE `tb_tipos_paginas` SET `ORDEM_MENU` = '2' WHERE (`COD_TIPO` = '200');
UPDATE `tb_tipos_paginas` SET `ORDEM_MENU` = '3' WHERE (`COD_TIPO` = '300');
UPDATE `tb_tipos_paginas` SET `ORDEM_MENU` = '4' WHERE (`COD_TIPO` = '100');
--
INSERT INTO `tb_paginas` (`COD_PAGINA`, `NOME_PAGINA`, `NOME_CONTROLADOR`, `FLG_ATIVO`, `COD_TIPO`, `FLG_TIPO_PAGINA`) VALUES ('3001', 'Reports', 'CD_Reports', 'S', '300', 'C');
UPDATE `tb_paginas` SET `NOME_PAGINA` = 'Reports Fake' WHERE (`COD_PAGINA` = '3000');
--
ALTER TABLE TB_JOBS_ORDEM ADD INDEX TB_JOBS_ORDEM_IDX01 (COD_EMPRESA,JOB_NUM);
ALTER TABLE TB_ORDEM ADD INDEX TB_ORDEM_IDX01 (COD_EMPRESA,STATUS,DATA_BAIXA);
--
ALTER TABLE tb_ordem CHANGE ZAIP_CODE ZIP_CODE varchar(20) DEFAULT NULL;
