SELECT * FROM work_order.tb_usuarios;
--
-- CADASTRO DE USUARIO
ALTER TABLE tb_usuarios ADD COLUMN FLG_SUBMANAGER VARCHAR(1) NOT NULL DEFAULT 'N' COMMENT 'Determina se o usuario e um submanger de mercado';
--
-- CADASTRO DE JOB E JOB USUARIO
SELECT * FROM tb_job;
ALTER TABLE tb_job ADD COLUMN VALOR_SUBMANAGER_DEDUCTION DECIMAL(10,2) NOT NULL DEFAULT 0;
ALTER TABLE tb_job ADD COLUMN VALOR_SUBMANAGER_RATE DECIMAL(10,2) NOT NULL DEFAULT 0;
--
ALTER TABLE tb_jobs_usuario ADD COLUMN VALOR_SUBMANAGER_DEDUCTION DECIMAL(10,2) NOT NULL DEFAULT 0;
ALTER TABLE tb_jobs_usuario ADD COLUMN VALOR_SUBMANAGER_RATE DECIMAL(10,2) NOT NULL DEFAULT 0;
--
ALTER TABLE tb_jobs_ordem ADD COLUMN VALOR_SUBMANAGER_DEDUCTION DECIMAL(10,2) NOT NULL DEFAULT 0;
ALTER TABLE tb_jobs_ordem ADD COLUMN VALOR_SUBMANAGER_RATE DECIMAL(10,2) NOT NULL DEFAULT 0;
--
show create trigger NOVO_JOB;
--
DROP TRIGGER IF EXISTS NOVO_JOB;
--
CREATE DEFINER=`root`@`localhost` TRIGGER NOVO_JOB
  AFTER INSERT
  ON TB_JOB FOR EACH ROW
  INSERT INTO TB_JOBS_USUARIO (COD_JOB, COD_EMPRESA, COD_USUARIO, VALOR_PAG, VALOR_REC, QTD_MAX, QTD_MIN, FLG_ATIVO, COD_FILIAL, VALOR_REP, VALOR_DESC, VALOR_FDR, VALOR_FID, VALOR_SUBMANAGER_DEDUCTION,VALOR_SUBMANAGER_RATE)
  SELECT 
     NEW.COD_JOB, US.COD_EMPRESA, US.COD_USUARIO, NEW.VALOR_PAG, NEW.VALOR_REC, NEW.QTD_MAX, NEW.QTD_MIN, NEW.FLG_ATIVO, NEW.COD_FILIAL, NEW.VALOR_REP, NEW.VALOR_DESC, NEW.VALOR_FDR, NEW.VALOR_FID, NEW.VALOR_SUBMANAGER_DEDUCTION, NEW.VALOR_SUBMANAGER_RATE
  FROM 
     TB_USUARIOS AS US 
     WHERE US.COD_EMPRESA = NEW.COD_EMPRESA 
     AND NEW.COD_FILIAL IN (SELECT COD_FILIAL FROM TB_USUARIO_FILIAL WHERE COD_USUARIO = US.COD_USUARIO AND US.COD_EMPRESA = NEW.COD_EMPRESA);
--

/* BKP PRD
CREATE DEFINER=`dba`@`%` TRIGGER NOVO_JOB
  AFTER INSERT
  ON TB_JOB FOR EACH ROW
  INSERT INTO TB_JOBS_USUARIO (COD_JOB, COD_EMPRESA, COD_USUARIO, VALOR_PAG, VALOR_REC, QTD_MAX, QTD_MIN, FLG_ATIVO, COD_FILIAL, VALOR_REP, VALOR_DESC, VALOR_FDR, VALOR_FID)
  SELECT 
     NEW.COD_JOB, US.COD_EMPRESA, US.COD_USUARIO, NEW.VALOR_PAG, NEW.VALOR_REC, NEW.QTD_MAX, NEW.QTD_MIN, NEW.FLG_ATIVO, NEW.COD_FILIAL, NEW.VALOR_REP, NEW.VALOR_DESC, NEW.VALOR_FDR, NEW.VALOR_FID
  FROM 
     TB_USUARIOS AS US WHERE US.COD_EMPRESA = NEW.COD_EMPRESA AND NEW.COD_FILIAL IN (SELECT COD_FILIAL FROM TB_USUARIO_FILIAL WHERE COD_USUARIO = US.COD_USUARIO AND US.COD_EMPRESA = NEW.COD_EMPRESA)
*/